import type {Metadata} from 'next';
import {Wrapper} from '../components/Wrapper';

import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import 'slick-carousel/slick/slick-theme.css';
import 'slick-carousel/slick/slick.css';
import '../styles/custom.scss';
import '../styles/globals.scss';
import '../styles/mixins.scss';

export const metadata: Metadata = {
    title: 'Gravity UI – Next.js App Example',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="ru">
            <body className={'app'}>
                <Wrapper>{children}</Wrapper>
            </body>
        </html>
    );
}
